//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeEstacionamientos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APARCAMIENTO
    {
        public int ID_APARCAMIENTO { get; set; }
        public System.DateTime FECHA_ENTRADA { get; set; }
        public System.TimeSpan HORA_ENTRADA { get; set; }
        public Nullable<System.DateTime> FECHA_SALIDA { get; set; }
        public Nullable<System.TimeSpan> HORA_SALIDA { get; set; }
        public string PATENTE_VEHICULO { get; set; }
    
        public virtual VEHICULO VEHICULO { get; set; }
    }
}
