//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeEstacionamientos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLETA
    {
        public int ID_BOLETA { get; set; }
        public int ID_SALIDA { get; set; }
        public string TOTAL_A_PAGAR { get; set; }
    
        public virtual SALIDA SALIDA { get; set; }
    }
}
