//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeEstacionamientos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGRESO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INGRESO()
        {
            this.SALIDA = new HashSet<SALIDA>();
        }
    
        public int ID_INGRESO { get; set; }
        public System.DateTime FECHA_ENTRADA { get; set; }
        public System.TimeSpan HORA_ENTRADA { get; set; }
        public string ESTADO { get; set; }
        public string PATENTE_VEHICULO { get; set; }
    
        public virtual VEHICULO VEHICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALIDA> SALIDA { get; set; }
    }
}
