CREATE DATABASE ESTACIONAMIENTO

USE ESTACIONAMIENTO

CREATE TABLE USUARIO(
ID_USUARIO INT IDENTITY(1000,1) PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
NOMBRE_USUARIO VARCHAR(50) NOT NULL, 
CONTRASENIA VARCHAR(20) NOT NULL)

CREATE TABLE VEHICULO(
PATENTE VARCHAR (8) PRIMARY KEY NOT NULL,
MODELO VARCHAR(50) NOT NULL,
MARCA VARCHAR(50) NOT NULL
)

CREATE TABLE APARCAMIENTO(
ID_APARCAMIENTO INT IDENTITY (1000,1) PRIMARY KEY NOT NULL,
FECHA_ENTRADA DATE NOT NULL,
HORA_ENTRADA TIME NOT NULL,
FECHA_SALIDA DATE,
HORA_SALIDA TIME,
PATENTE_VEHICULO VARCHAR(8) NOT NULL
)


ALTER TABLE APARCAMIENTO
ADD CONSTRAINT FK_APAR
FOREIGN KEY (PATENTE_VEHICULO) REFERENCES VEHICULO(PATENTE)
